name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  test:
    name: ${{ matrix.lisp }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        lisp: [sbcl-bin]

    steps:
      - uses: actions/checkout@v2
      - name: Install ASDF
        run: |
          mkdir ~/common-lisp
          git clone --depth 1 -b 3.3.5.3 https://gitlab.common-lisp.net/asdf/asdf.git ~/common-lisp/asdf
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
      - name: Install fiveam
        run: ros install fiveam
      - name: Run tests
        run: |
          ros -s fiveam -e '(handler-bind ((error (lambda (c) (print c) (uiop:quit 1))))
                              (ql:quickload :tictactoe/test))
                            (handler-bind ((error (lambda (c) (print c) (uiop:quit 1))))
                              (or (fiveam:run! (quote tictactoe/test:main-suite))
                                  (uiop:quit 1)))'
